language: c++

compiler:
    - clang

script:
    - if [[ $CC == "clang" ]]; then export CC=`which clang`; fi
    - if [[ $CXX == "clang++" ]]; then export CXX=`which clang++`; fi
    - "cd src/third_party/glog && ln -snf config.linux config.h && cd -"
    - scons -Q
    - src/all_test
